default:
  image: "archlinux:latest"

stages:
  - lint
  - vars
  - clean
  - build
  - test
  - release
  - cleanup
  - report

codespell:
  stage: lint
  tags:
    - docker
  before_script:
    - pacman -Syu --needed --noconfirm codespell
  script:
    - codespell --enable-colors
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
    - if: '$CI_PIPELINE_SOURCE == "schedule"'

markdownlint:
  stage: lint
  tags:
    - docker
  before_script:
    - pacman -Syu --needed --noconfirm markdownlint
  script:
    - mdl --style .mdl_style.rb .
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
    - if: '$CI_PIPELINE_SOURCE == "schedule"'

shellcheck:
  stage: lint
  tags:
    - docker
  before_script:
    - pacman -Syu --needed --noconfirm shellcheck
  script:
    - find . -name '*.sh*' -exec shellcheck --color=always {} +
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
    - if: '$CI_PIPELINE_SOURCE == "schedule"'

.set-variables:
  stage: vars
  script:
    - |
      IMAGE_VERSION=$(date +'%Y.%m.%d')."${CI_PIPELINE_ID}"
      PACKAGE_REGISTRY_URL="${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/image/${IMAGE_VERSION}"
      GEO_MIRROR_URL="https://geo.mirror.pkgbuild.com/wsl/${IMAGE_VERSION}"
      echo "IMAGE_VERSION=${IMAGE_VERSION}" > variables.env
      echo "PACKAGE_REGISTRY_URL=${PACKAGE_REGISTRY_URL}" >> variables.env
      echo "GEO_MIRROR_URL=${GEO_MIRROR_URL}" >> variables.env
  artifacts:
    reports:
      dotenv: variables.env

set-variables:
  extends: .set-variables
  tags:
    - docker
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'

set-variables:secure:
  extends: .set-variables
  tags:
    - docker
    - secure
  rules:
    - if: '$CI_PIPELINE_SOURCE == "schedule"'

.make-clean:
  stage: clean
  before_script:
    - pacman -Syu --needed --noconfirm make
  script:
    - make clean

make-clean:
  extends: .make-clean
  tags:
    - docker
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'

make-clean:secure:
  extends: .make-clean
  tags:
    - docker
    - secure
  rules:
    - if: '$CI_PIPELINE_SOURCE == "schedule"'

.make-build:
  stage: build
  variables:
    COSIGN_YES: "true"
  id_tokens:
    SIGSTORE_ID_TOKEN:
      aud: sigstore
  before_script:
    - pacman -Syu --needed --noconfirm make devtools fakechroot fakeroot cosign
  script:
    - make build IMAGE_VERSION="${IMAGE_VERSION}"
    - cosign sign-blob "workdir/output/archlinux-${IMAGE_VERSION}.wsl" --bundle "workdir/output/archlinux-${IMAGE_VERSION}.wsl.bundle"
  artifacts:
    paths:
      - workdir/*
    expire_in: 1h

make-build:
  extends: .make-build
  tags:
    - docker
  needs:
    - make-clean
    - set-variables
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'

make-build:secure:
  extends: .make-build
  tags:
    - docker
    - secure
  needs:
    - make-clean:secure
    - set-variables:secure
  rules:
    - if: '$CI_PIPELINE_SOURCE == "schedule"'

.make-test:
  stage: test
  before_script:
    - pacman -Syu --needed --noconfirm make fakechroot fakeroot git python cosign
  script:
    - make test IMAGE_VERSION="${IMAGE_VERSION}"
    - cd workdir/output/
    - sha256sum --check "archlinux-${IMAGE_VERSION}.wsl.SHA256"
    - cosign verify-blob archlinux-${IMAGE_VERSION}.wsl --bundle archlinux-${IMAGE_VERSION}.wsl.bundle --certificate-identity "${CI_PROJECT_URL}//.gitlab-ci.yml@refs/heads/${CI_COMMIT_REF_NAME}" --certificate-oidc-issuer "https://gitlab.archlinux.org"

make-test:
  extends: .make-test
  tags:
    - docker
  needs:
    - make-build
    - set-variables
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'

make-test:secure:
  extends: .make-test
  tags:
    - docker
    - secure
  needs:
    - make-build:secure
    - set-variables:secure
  rules:
    - if: '$CI_PIPELINE_SOURCE == "schedule"'

upload-artifacts:
  stage: release
  tags:
    - docker
    - secure
  needs:
    - make-build:secure
    - make-test:secure
    - set-variables:secure
  script:
    - | 
      echo "Uploading archlinux-${IMAGE_VERSION}.wsl"
      curl -sSf --header "JOB-TOKEN: ${CI_JOB_TOKEN}" --upload-file "workdir/output/archlinux-${IMAGE_VERSION}.wsl" "${PACKAGE_REGISTRY_URL}/"
      echo "Uploading archlinux-${IMAGE_VERSION}.wsl.SHA256"
      curl -sSf --header "JOB-TOKEN: ${CI_JOB_TOKEN}" --upload-file "workdir/output/archlinux-${IMAGE_VERSION}.wsl.SHA256" "${PACKAGE_REGISTRY_URL}/"
      echo "Uploading archlinux-${IMAGE_VERSION}.wsl.bundle"
      curl -sSf --header "JOB-TOKEN: ${CI_JOB_TOKEN}" --upload-file "workdir/output/archlinux-${IMAGE_VERSION}.wsl.bundle" "${PACKAGE_REGISTRY_URL}/"
  rules:
    - if: '$CI_PIPELINE_SOURCE == "schedule"'

publish-WSL:
  stage: release
  tags:
    - docker
    - secure
  needs:
    - upload-artifacts
    - set-variables:secure
  before_script:
    - pacman -Syu --needed --noconfirm git github-cli jq
    - git config --global user.email "github@archlinux.org"
    - git config --global user.name "Arch Linux Technical User"
    - gh auth status
    - curl -sSf --head "${GEO_MIRROR_URL}/archlinux-${IMAGE_VERSION}.wsl" || { echo "Latest image version not synced to geo mirror"; exit 1; }
    - IMAGE_CHECKSUM=$(curl -sf "${GEO_MIRROR_URL}/archlinux-${IMAGE_VERSION}.wsl.SHA256" | awk '{print $1} END {if ($1=="") exit 1}')
  script:
    - echo "Update the WSL GitHub repo"
    - mkdir WSL
    - cd WSL
    - git init
    - git remote add origin "https://x-access-token:${GITHUB_TOKEN}@github.com/archlinux/WSL.git"
    - git fetch https://github.com/microsoft/WSL.git
    - git reset --hard FETCH_HEAD
    - head="release/${IMAGE_VERSION}"
    - git switch -c "$head"
    - jq --indent 4
        '.ModernDistributions.archlinux[0].Amd64Url.Url = "'${GEO_MIRROR_URL}'/archlinux-'${IMAGE_VERSION}'.wsl" |
         .ModernDistributions.archlinux[0].Amd64Url.Sha256 = "'${IMAGE_CHECKSUM}'"'
        distributions/DistributionInfo.json > /tmp/DistributionInfo.json
    - mv -f /tmp/DistributionInfo.json distributions/DistributionInfo.json
    - git diff
    - git add distributions/DistributionInfo.json
    - 'git commit
        -m "archlinux: Release ${IMAGE_VERSION}"
        -m "This is an automated release [1]."
        -m "[1] ${CI_PROJECT_URL}/-/blob/${CI_DEFAULT_BRANCH}/.gitlab-ci.yml"'
    - git push -u origin "$head"
    - 'gh pr create
        --repo microsoft/WSL
        --title "$(git show --no-patch --format="%s")"
        --body "$(printf "%s\n\n---\n\nMaintainers: @Antiz96 @mhegreberg\n" "$(git show --no-patch --format="%b")")"
        --base master
        --head archlinux:"$head"'
  rules:
    - if: '$CI_PIPELINE_SOURCE == "schedule"'
      when: delayed
      start_in: 2 hours

cleanup-pkg-registry:
  stage: cleanup
  tags:
    - docker
    - secure
  needs:
    - publish-WSL
  before_script:
    - pacman -Syu --needed --noconfirm jq
  script:
    - |
      for id in $(curl --silent --fail --show-error "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages?per_page=100&order_by=created_at&sort=asc" | jq '.[] | select(.created_at | split("T")[0] | . < (now-60*60*24*90|strflocaltime("%Y-%m-%d"))) | .id'); do
        curl --silent --fail --show-error --request DELETE --header "PRIVATE-TOKEN: ${GITLAB_PROJECT_TOKEN}" "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/${id}"
      done
  rules:
    - if: '$CI_PIPELINE_SOURCE == "schedule"'

issue-bot:
  stage: report
  tags:
    - secure
    - docker
  image: registry.gitlab.com/gitlab-org/distribution/issue-bot:latest
  script: /issue-bot
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
      when: on_failure
