default:
  image: "archlinux:latest"

stages:
  - lint
  - clean
  - build
  - release

codespell:
  stage: lint
  before_script:
    - pacman -Syu --needed --noconfirm codespell
  script:
    - codespell --enable-colors
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'

markdownlint:
  stage: lint
  before_script:
    - pacman -Syu --needed --noconfirm markdownlint
  script:
    - mdl --style .mdl_style.rb .
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'

shellcheck:
  stage: lint
  before_script:
    - pacman -Syu --needed --noconfirm shellcheck
  script:
    - find . -name '*.sh*' -exec shellcheck --color=always {} +
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'

make-clean:
  stage: clean
  before_script:
    - pacman -Syu --needed --noconfirm make
  script:
    - make clean
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
    - if: '$CI_PIPELINE_SOURCE == "schedule"'

make-build:
  stage: build
  before_script:
    - pacman -Syu --needed --noconfirm make devtools fakechroot fakeroot
  script:
    - make build
  artifacts:
    paths:
      - output/*
    expire_in: 2h
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
    - if: '$CI_PIPELINE_SOURCE == "schedule"'

upload-image-to-package-registry:
  stage: release
  needs:
    - make-clean
    - make-build
  script:
    - | 
      export IMAGE_VERSION=$(date +"%Y.%m.%d")
      export PACKAGE_REGISTRY_URL="${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/image/${IMAGE_VERSION}"
      echo "Uploading archlinux-${IMAGE_VERSION}.wsl"
      curl -sSf --header "JOB-TOKEN: ${CI_JOB_TOKEN}" --upload-file "output/archlinux-${IMAGE_VERSION}.wsl" "${PACKAGE_REGISTRY_URL}/"
      echo "Uploading archlinux-${IMAGE_VERSION}.wsl.SHA256"
      curl -sSf --header "JOB-TOKEN: ${CI_JOB_TOKEN}" --upload-file "output/archlinux-${IMAGE_VERSION}.wsl.SHA256" "${PACKAGE_REGISTRY_URL}/"
  rules:
    - if: '$CI_PIPELINE_SOURCE == "schedule"'
