default:
  image: "archlinux:latest"

stages:
  - lint
  - clean
  - build
  - release

codespell:
  stage: lint
  before_script:
    - pacman -Syu --needed --noconfirm codespell
  script:
    - codespell --enable-colors
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'

markdownlint:
  stage: lint
  before_script:
    - pacman -Syu --needed --noconfirm markdownlint
  script:
    - mdl --style .mdl_style.rb .
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'

shellcheck:
  stage: lint
  before_script:
    - pacman -Syu --needed --noconfirm shellcheck
  script:
    - find . -name '*.sh*' -exec shellcheck --color=always {} +
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'

make-clean:
  stage: clean
  before_script:
    - pacman -Syu --needed --noconfirm make
  script:
    - make clean
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
    - if: '$CI_PIPELINE_SOURCE == "schedule"'

make-build:
  stage: build
  before_script:
    - pacman -Syu --needed --noconfirm make
  script:
    - make build
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
    - if: '$CI_PIPELINE_SOURCE == "schedule"'

create-release:
  stage: release
  needs:
    - make-clean
    - make-build
  script:
    - echo "Hello"
  rules:
    - if: '$CI_PIPELINE_SOURCE == "schedule"'
